### ISSUE TITLE
SignIn is not a constructor

### ISSUE THREAD

**Issue by thadumi** [actions-on-google/actions-on-google-nodejs#141]
Hi,
I'm trying to make a SignIn request but I revive every time the following error:
```
      TypeError: SignIn is not a constructor     
      at helloHandler (/user_code/index.js:30:17)     
      at WebhookClient.handleRequest (/user_code/node_modules/dialogflow-fulfillment/src/dialogflow-fulfillment.js:251:44)    
      at exports.logintest.functions.https.onRequest (/user_code/index.js:66:9)     
      at cloudFunction (/user_code/node_modules/firebase-functions/lib/providers/https.js:26:47)     at /var/tmp/worker/worker.js:686:7     
      at /var/tmp/worker/worker.js:670:9     
      at _combinedTickCallback (internal/process/next_tick.js:73:7)     
      at process._tickDomainCallback (internal/process/next_tick.js:128:9) | more_vert
-- | --
```

I wrote something like this:
```
exports.logintest = functions.https.onRequest((request, response) => {
  const agent = new WebhookClient({ request, response });
   .....
  function helloHandler(agent) {
       let conv = agent.conv();
       conv.ask(new SignIn());
       agent.add(conv);
 }
}
   
```
As AccountLinking I set up an auth0 application.

**Comment by dharmendra** [comment]
I am facing same issue, could you please help me to resolve this one.

**Comment by Fleker** [comment]
You probably need to include it when you import the dependency:

```
const {
  dialogflow,
  SignIn,
} = require('actions-on-google')
```
