### ISSUE TITLE
Asking for account linking fails "ReferenceError: SignIn is not defined"

### ISSUE THREAD

**Issue by rampency** [actions-on-google/actions-on-google-nodejs#161]
I'm migrating the code over and i can't get my account linking sign in process to work. After looking at the documentation and code i don't see any error in the way i'm calling SignIn(). 
I've also made sure to update action.json and add the v2 account linking stuff in there, and my app always had account linking working so the account linking section in the Console is up to date.

```
const {actionssdk} = require('actions-on-google');
const app = actionssdk({debug: true});
app.intent('actions.intent.MAIN', conv => {
  conv.ask(new SignIn())
})

app.intent('actions.intent.SIGN_IN', (conv, input, signin) => {
  if (signin.status === 'OK') {
    const access = conv.user.access.token // possibly do something with access token
     conv.ask('Great, thanks for signing in! What do you want to do next?')
    } else {
      conv.ask(`I won't be able to save your data, but what do you want to do next?`)
    }
})
module.exports.assistant = app;

```

```
ReferenceError: SignIn is not defined
    at app.intent.conv (/usr/local/lucida/web/client-apps/src/routes/google_home.js:4:16)
    at Function.<anonymous> (/usr/local/lucida/web/client-apps/node_modules/actions-on-google/dist/service/actionssdk/actionssdk.js:138:23)
    at next (native)
    at /usr/local/lucida/web/client-apps/node_modules/actions-on-google/dist/service/actionssdk/actionssdk.js:22:71
    at __awaiter (/usr/local/lucida/web/client-apps/node_modules/actions-on-google/dist/service/actionssdk/actionssdk.js:18:12)
    at Function.handler (/usr/local/lucida/web/client-apps/node_modules/actions-on-google/dist/service/actionssdk/actionssdk.js:85:16)
    at Object.<anonymous> (/usr/local/lucida/web/client-apps/node_modules/actions-on-google/dist/assistant.js:55:32)
    at next (native)
    at /usr/local/lucida/web/client-apps/node_modules/actions-on-google/dist/assistant.js:22:71
    at __awaiter (/usr/local/lucida/web/client-apps/node_modules/actions-on-google/dist/assistant.js:18:12)
    at standard (/usr/local/lucida/web/client-apps/node_modules/actions-on-google/dist/assistant.js:51:41)
    at /usr/local/lucida/web/client-apps/node_modules/actions-on-google/dist/framework/express.js:23:13
    at omni (/usr/local/lucida/web/client-apps/node_modules/actions-on-google/dist/assistant.js:44:53)
    at Layer.handle [as handle_request] (/usr/local/lucida/web/client-apps/node_modules/express/lib/router/layer.js:95:5)
    at next (/usr/local/lucida/web/client-apps/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/usr/local/lucida/web/client-apps/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/usr/local/lucida/web/client-apps/node_modules/express/lib/router/layer.js:95:5)
    at /usr/local/lucida/web/client-apps/node_modules/express/lib/router/index.js:281:22
    at param (/usr/local/lucida/web/client-apps/node_modules/express/lib/router/index.js:354:14)
    at param (/usr/local/lucida/web/client-apps/node_modules/express/lib/router/index.js:365:14)
    at Function.process_params (/usr/local/lucida/web/client-apps/node_modules/express/lib/router/index.js:410:3)
    at next (/usr/local/lucida/web/client-apps/node_modules/express/lib/router/index.js:275:10)

```

**Comment by Phaael** [comment]
Try put this:
const { actionssdk, SignIn } = require('actions-on-google');
usually you must declare SignIn on require

**Comment by peternann** [comment]
Yeah, it's really annoying that sample code all over the place just uses "new SignIn()" without giving any clue where the class may be found.
We are developers, not mind-readers...
