### ISSUE TITLE
Looks like Actions SDK is not closing the request with async methods gracefully!

### ISSUE THREAD

**Issue by phani1kumar** [actions-on-google/actions-on-google-nodejs#245]
https://stackoverflow.com/questions/53154510/google-actions-sdk-second-request-in-conversation-is-failing-with-typeerror-st

I am building a Google Action using Actions SDK V2 library. 

I am able to make the conversation work when I am using plain conv.ask and conv.close methods. But the moment I add async methods in to the processing chain, I am facing issues. I am using 

```
    "actions-on-google": "^2.4.1", 
    "firebase-admin": "^6.0.0",
    "firebase-functions": "^2.1.0",
```

Exactly after every 3 failed attempts, the 4th attempt gets through. Looks like the previous request is hogging up my firebase cloud function!

First request to the fulfillment works just fine and the subsequent ones fail with "TypeError: standard is not a function at /srv/node_modules/actions-on-google/dist/framework/express.js"

 ```
   severity:  "ERROR"  
     textPayload:  "TypeError: standard is not a function
        at /srv/node_modules/actions-on-google/dist/framework/express.js:27:13
        at omni (/srv/node_modules/actions-on-google/dist/assistant.js:44:53)
        at cloudFunction (/srv/node_modules/firebase-functions/lib/providers/https.js:57:9)
        at /worker/worker.js:700:7
        at /worker/worker.js:684:9
        at _combinedTickCallback (internal/process/next_tick.js:131:7)
        at process._tickDomainCallback (internal/process/next_tick.js:218:9)" 
```

I understand that when I've asynchronous functions in the processing chain, I should return Promise to the Intent handler. And I am doing that. But still the subsequent request fails.

  ```
  const app = actionssdk();
     // ... app code here
    
    
      app.middleware((conv) => {
        console.log('Conversation in Middleware:', conv);
        conv.hasScreen =
          conv.surface.capabilities.has('actions.capability.SCREEN_OUTPUT');
        conv.hasAudioPlayback =
          conv.surface.capabilities.has('actions.capability.AUDIO_OUTPUT');
      });

    // Welcome Intent
    app.intent('actions.intent.MAIN', (conv, input) => {
      // conv.ask('How are you');
      console.log('Conversation: ' + JSON.stringify(conv), conv);
      console.log('actions.intent.MAIN', input)
      return new Promise((resolve, reject) => {
        processIntents({conv: conv, input:input}).then(r => {
          console.log('Passing response from the handler!', r);
          for(let a of r) {
            conv.ask(a);
          }
          resolve();
        }).catch(e => reject(e));
      });
    });

    // React to a text intent
    app.intent('actions.intent.TEXT', (conv, input) => {
      console.log('actions.intent.TEXT', input)
      // conv.ask('How are you');
      console.log('Conversation: ' + JSON.stringify(conv), conv);
      console.log('actions.intent.TEXT', input)
      return new Promise((resolve, reject) => {
        processIntents({conv: conv, input:input}).then(r => {
          console.log('Passing response from the handler!', r);
          for(let a of r) {
            conv.ask(a);
          }
          resolve();
        }).catch(e => reject(e));
      });
    });
    
    // React to list or carousel selection
    app.intent('actions.intent.OPTION', (conv, params, option) => {
      // conv.ask('How are you');
      console.log('actions.intent.OPTION', {input: conv.input, option: option, params:params})
      console.log('Conversation: ' + JSON.stringify(conv), conv);
      console.log('actions.intent.OPTION', option)
      return new Promise((resolve, reject) => {
        processIntents({conv: conv, params: params, option: option}).then(r => {
          console.log('Passing response from the handler!', r);
          for(let a of r) {
            conv.ask(a);
          }
          resolve();
        }).catch(e => reject(e));
      });
    });
    app.intent('', (conv) => {
      // conv.ask('How are you');
      console.log('Empty Intent for direct WEB requests / ALEXA requests', conv);
      let input = ((conv.request.originalRequest ||{}).result ||{}).resolvedQuery;
      return new Promise((resolve, reject) => {
        processIntents({conv: conv, input: input}).then(r => {
          //TODO: send raw HTTP Response
          //TODO: Yet to figure out how this can be done@!
          resolve();
        }).catch(e => reject(e));
      });
    });
    
    const processIntents = (args) => {
        let conv = args["conv"];
        let params = args["params"];
        let option = args["option"];
        let input = args["input"];
        // Async Function here that responds with a Promise
        // Based on the request, it will send either array of responses to use in conv.ask calls
       // OR send response JSON body that can be sent to Amazon Alexa / WEB requests
      return Promise.resolve(response);
    }
    exports.apiaifns = functions.https.onRequest(app);
```

 I am sending an array of conversation responses from the `processIntents` method and iterating through the array while responding. 

I've tried many possible permutations and combinations of this, but still the subsequent request fails. 

**Update : Testing with Google Cloud Functions instead of GCF for Firebase**
Updated my app code to make it an express app and deployed to GCFs with the same name. Now the situatio is **worse**. Only first request after deployment of the Cloud Function is successful and all subsequent requests fail with the same error as before!

Here is my update to the function:

    ```
    const express = require('express')
    const bodyParser = require('body-parser')
    var morgan = require('morgan')
    .
    .
    .
    const expressApp = express().use(bodyParser.json())
    expressApp.use(morgan('dev'))
    expressApp.post('/fulfillment', app)
    
    exports.apiaifns = functions.https.onRequest(expressApp);
```
I've also changed the actio invocation URL to "https://us-central1-my-project.cloudfunctions.net/apiaifns/fulfillment"

This is litarally driving me crazzy, and I couldn't find a reason for the issue! Kindly help.

**Comment by maaaaaaaax** [comment]
Due to more than 5 months of inactivity, this issue is being closed. 

If you think the resolution is in error, please re-open the request with fresh information.
