### ISSUE TITLE
error while signing in

### ISSUE THREAD

**Issue by rrrepos** [actions-on-google/actions-on-google-nodejs#274]
I am trying to use the helper `SignIn` intent. After setting it in the actions console and calling it using 
`conv.ask(new SignIn())`, the assistant does go through the permissions granting process. However, at the end of it I am getting the following error on the server console.

```
TypeError: Cannot read property 'client' of undefined
    at Function.<anonymous> (/Users/rr/Documents/GitHub/eda-app/node_modules/actions-on-google/dist/service/actionssdk/actionssdk.js:113:72)
    at Generator.next (<anonymous>)
    at /Users/rr/Documents/GitHub/eda-app/node_modules/actions-on-google/dist/service/actionssdk/actionssdk.js:22:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/rr/Documents/GitHub/eda-app/node_modules/actions-on-google/dist/service/actionssdk/actionssdk.js:18:12)
    at Function.handler (/Users/rr/Documents/GitHub/eda-app/node_modules/actions-on-google/dist/service/actionssdk/actionssdk.js:85:16)
    at Object.<anonymous> (/Users/rr/Documents/GitHub/eda-app/node_modules/actions-on-google/dist/assistant.js:55:32)
    at Generator.next (<anonymous>)
    at /Users/rr/Documents/GitHub/eda-app/node_modules/actions-on-google/dist/assistant.js:22:71
    at new Promise (<anonymous>)
```

What could this be due to? Thanks

**Comment by rrrepos** [comment]
Oops, just realised that I need to put the client-id in the instantiation of the app

```
const app = actionssdk({
  clientId: <YOUR_CLIENT_ID>
});
```

My bad.
