### ISSUE TITLE
Not able to create Table card in google assistant (Inline editor)

### ISSUE THREAD

**Issue by aloksoni88** [actions-on-google/actions-on-google-nodejs#285]
Below is the code i am written but form the firebase log i am getting below error
TypeError: Table is not a constructor
    at showTable (/user_code/index.js:74:15)
    at WebhookClient.handleRequest (/user_code/node_modules/dialogflow-fulfillment/src/dialogflow-fulfillment.js:303:44)
    at exports.dialogflowFirebaseFulfillment.functions.https.onRequest (/user_code/index.js:102:9)
    at cloudFunction (/user_code/node_modules/firebase-functions/lib/providers/https.js:57:9)
    at /var/tmp/worker/worker.js:735:7
    at /var/tmp/worker/worker.js:718:11
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickDomainCallback (internal/process/next_tick.js:128:9)

below is the code i am using
agent.add(new Table({
  	dividers: true,
  	columns: ['header 1', 'header 2', 'header 3'],
  	rows: [
    	['row 1 item 1', 'row 1 item 2', 'row 1 item 3'],
    	['row 2 item 1', 'row 2 item 2', 'row 2 item 3'],
  	],
	}));

**Comment by Fleker** [comment]
It looks like you're using the Dialogflow fulfillment library instead of the Actions on Google library. You need to use one or the other, you cannot use both interchangably.

**Comment by aloksoni88** [comment]
ok Got it. Thanks a lot. Now my question is using dialogflow fulfillment how can i make table card?

**Comment by aloksoni88** [comment]
How can i create BasicCard using dialogflow fulfillment

**Comment by Fleker** [comment]
You'll need to look into using the JSON representation: https://dialogflow.com/docs/reference/message-objects#table_card
