### ISSUE TITLE
problem with variable name "request" and "response"

### ISSUE THREAD

**Issue by Iridio** [actions-on-google/actions-on-google-nodejs#30]
Using express.js if I create an handler like this
```
const express = require("express");
const App = require("actions-on-google").ApiAiApp;
const router = express.Router();
const CULTURE_US = 'en-US';

router.post('/en-US', (request, response) => {
    function handleActions(appApi) {
        processApiAiRequest(appAi, CULTURE_US);
    }
    console.log('Request body', request.body);
    const appAi = new App({ request, response });
    appAi.handleRequest(handleActions);
});

function processApiAiRequest(appAi, culture) {
    let intent = appAi.getIntent();
    let paramValue = appAi.getArgument('fabric');
    let surfaceCapability = appAi.hasSurfaceCapability(appAi.SurfaceCapabilities.SCREEN_OUTPUT) ? 'yes' : 'no';
    appAi.ask('culture: ' + culture + 'intent: ' + intent + ' params:' + paramValue + ' screen capability: ' + surfaceCapability);
}

module.exports = router; 
```

the code works perfectly, but if I change the code like this it does not:

```
const express = require("express");
const App = require("actions-on-google").ApiAiApp;
const router = express.Router();
const CULTURE_US = 'en-US';

router.post('/it-it', (req, res) => {
    function handleActions(appApi) {
        processApiAiRequest(appAi, CULTURE_IT);
    }
    console.log('Request body', req.body);
    const appAi = new App({ req, res });
    appAi.handleRequest(handleActions);
});

function processApiAiRequest(appAi, culture) {
    let intent = appAi.getIntent();
    let paramValue = appAi.getArgument('fabric');
    let surfaceCapability = appAi.hasSurfaceCapability(appAi.SurfaceCapabilities.SCREEN_OUTPUT) ? 'yes' : 'no';
    appAi.ask('culture: ' + culture + 'intent: ' + intent + ' params:' + paramValue + ' screen capability: ' + surfaceCapability);
}

module.exports = router; 
```
Basically if I name the variables "req" and "res" instead of "request" and "response" I got following error:
```
2017-06-23T14:03:20.330203+00:00 app[web.1]: TypeError: Cannot read property 'result' of undefined
2017-06-23T14:03:20.330208+00:00 app[web.1]:     at ApiAiApp.handleRequest (/app/node_modules/actions-on-google/assistant-app.js:489:10)
2017-06-23T14:03:20.330207+00:00 app[web.1]:     at ApiAiApp.extractData_ (/app/node_modules/actions-on-google/api-ai-app.js:1405:19)
2017-06-23T14:03:20.330209+00:00 app[web.1]:     at router.post (/app/routes/webhooks.js:16:9)
2017-06-23T14:03:20.330210+00:00 app[web.1]:     at next (/app/node_modules/express/lib/router/route.js:137:13)
2017-06-23T14:03:20.330209+00:00 app[web.1]:     at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
2017-06-23T14:03:20.330212+00:00 app[web.1]:     at /app/node_modules/express/lib/router/index.js:281:22
2017-06-23T14:03:20.330211+00:00 app[web.1]:     at Route.dispatch (/app/node_modules/express/lib/router/route.js:112:3)
2017-06-23T14:03:20.330212+00:00 app[web.1]:     at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
2017-06-23T14:03:20.330213+00:00 app[web.1]:     at Function.process_params (/app/node_modules/express/lib/router/index.js:335:12)
2017-06-23T14:03:20.330214+00:00 app[web.1]:     at next (/app/node_modules/express/lib/router/index.js:275:10)

```

With the others handlers that do not use this module everything works both with "req" or "request"

the index.js is like this:
```
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express = require("express");
const bodyParser = require("body-parser");
const index = require("./routes/index");
const webHooks = require("./routes/webhooks"); //the handlers with the problem
const app = express();
app.use(bodyParser.urlencoded({ extended: false }));
app.use(bodyParser.json());
app.use('/', index);
app.use('/webhooks', webHooks);

var port = process.env.PORT || 3000;
app.listen(port, function () {
    console.log('Listening on port ' + port);
}); 
```

**Comment by Canain** [comment]
Hi,

This is because the [Assistant App](https://github.com/actions-on-google/actions-on-google-nodejs/blob/master/assistant-app.js#L74) is expecting an options variable which is expecting the properties of options to contain `request` and `response`.

These two lines:
```javascript
const appAi = new App({ request, response });
const appAi = new App({ req, res });
```
are giving completely different inputs

They are using [ES6 property definitions short notation](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Object_initializer) and are equivalent to:
```javascript
const appAi = new App({ request: request, response: response });
const appAi = new App({ req: req, res: res });
```

If you have variables with the names `req` and `res` that you want to pass in, then do:
```javascript
const appAi = new App({
  request: req,
  response: res
});
```

Can you elaborate on what you mean by `With the others handlers that do not use this module everything works both with "req" or "request"`?

**Comment by Iridio** [comment]
I get it, thanks for the prompt response. 
The last part was to try to give you as much info as possible, what I was trying to say, is that in the other hanlders, were I was using the variables req and res I was not getting any sort of problem.
If I may, I think could be nice to insert that in your documentation examples so it can be much more obvious also for people that are not so good with Javascript like me.
