### ISSUE TITLE
Issue after adding it with express

### ISSUE THREAD

**Issue by ishanbhutagate6** [actions-on-google/actions-on-google-nodejs#373]
` Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at Object.exports.stringify.exclude [as stringify] (/home/gate6/alexaDemo/node_modules/actions-on-google/dist/common.js:43:29)
    at Object.<anonymous> (/home/gate6/alexaDemo/node_modules/actions-on-google/dist/assistant.js:53:31)
    at Generator.next (<anonymous>)
    at /home/gate6/alexaDemo/node_modules/actions-on-google/dist/assistant.js:22:71
    at new Promise (<anonymous>)
    at __awaiter (/home/gate6/alexaDemo/node_modules/actions-on-google/dist/assistant.js:18:12)
    at standard (/home/gate6/alexaDemo/node_modules/actions-on-google/dist/assistant.js:51:51)
    at /home/gate6/alexaDemo/node_modules/actions-on-google/dist/framework/express.js:27:13
    at omni (/home/gate6/alexaDemo/node_modules/actions-on-google/dist/assistant.js:44:53)
    at Layer.handle [as handle_request] (/home/gate6/alexaDemo/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/gate6/alexaDemo/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/home/gate6/alexaDemo/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/home/gate6/alexaDemo/node_modules/express/lib/router/layer.js:95:5)
    at /home/gate6/alexaDemo/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/home/gate6/alexaDemo/node_modules/express/lib/router/index.js:335:12)`

**Comment by Fleker** [comment]
Please provide more info like what your setup is and the code you're running.

**Comment by ishanbhutagate6** [comment]
I am using a wrapper file app.js under which I have imported a index file in which I have used the code for getting request from webhook.
App.js
`var googleApp = require('./google/index');
app.post('/fulfillment', googleApp)`

index .js
`const {
  dialogflow,
  Image,
} = require('actions-on-google')`

When I have just import the file I got the above mentioned error every time when I hit the post api from my Diaglog flow simulator UI screen

**Comment by Fleker** [comment]
In your `index.js` are you exporting the `dialogflow` app variable that you create?

**Comment by ishanbhutagate6** [comment]
I had started the same with scratch now its working fine. Thanks

**Comment by mInzamamMalik** [comment]
I ran into the same error `"Cannot convert undefined or null to object at Function.keys..."`
it was happening because I forget to use body-parser, in firebase function body-parser is not required so they never mentioned in the docs, but it is required I think to parse the body.
