### ISSUE TITLE
Can't process request TypeError: Cannot read property 'result' of undefined  at ApiAiApp.extractData_ (/app/node_modules/actions-on-google/api-ai-app.js:1051:19)

### ISSUE THREAD

**Issue by emouawad** [actions-on-google/actions-on-google-nodejs#42]
2017-08-03T15:57:24.684034+00:00 app[web.1]: > telus-assistant@1.0.0 start /app
2017-08-03T15:57:24.684034+00:00 app[web.1]: > node index.js
2017-08-03T15:57:24.684035+00:00 app[web.1]: 
2017-08-03T15:57:24.952550+00:00 app[web.1]: Server listening
2017-08-03T15:57:25.891946+00:00 heroku[web.1]: State changed from starting to up
2017-08-03T15:58:04.247635+00:00 heroku[router]: at=info method=POST path="/hook" host=telusassistant.herokuapp.com request_id=6c256fe8-9eb1-4d31-9951-4f630b440a60 fwd="104.197.13.204" dyno=web.1 connect=0ms service=46ms status=400 bytes=296 protocol=https
2017-08-03T15:58:04.229272+00:00 app[web.1]: hook request
2017-08-03T15:58:04.229987+00:00 app[web.1]: Request headers: {"host":"telusassistant.herokuapp.com","connection":"close","accept":"*/*","content-type":"application/json; charset=UTF-8","user-agent":"Apache-HttpClient/4.5.2 (Java/1.8.0_131)","accept-encoding":"gzip,deflate","x-request-id":"6c256fe8-9eb1-4d31-9951-4f630b440a60","x-forwarded-for":"104.197.13.204","x-forwarded-proto":"https","x-forwarded-port":"443","via":"1.1 vegur","connect-time":"0","x-request-start":"1501775884200","total-route-time":"0","content-length":"590"}
2017-08-03T15:58:04.229989+00:00 app[web.1]: 
2017-08-03T15:58:04.229989+00:00 app[web.1]: 
2017-08-03T15:58:04.230077+00:00 app[web.1]: Request body: {"id":"918a62b3-c249-4c61-b9c6-25846f75f2af","timestamp":"2017-08-03T15:58:04.009Z","lang":"en","result":{"source":"agent","resolvedQuery":"channel down","speech":"","action":"input.cmd-channel","actionIncomplete":false,"parameters":{"sys-direction":"Down"},"contexts":[],"metadata":{"intentId":"1076649c-8560-4cc0-9568-62088cc9812a","webhookUsed":"true","webhookForSlotFillingUsed":"true","intentName":"cmd-channel"},"fulfillment":{"speech":"","messages":[{"type":0,"speech":""}]},"score":1},"status":{"code":200,"errorType":"success"},"sessionId":"1de54bbe-ca94-4c66-8595-004f4ef918c1"}
2017-08-03T15:58:04.230079+00:00 app[web.1]: 
2017-08-03T15:58:04.230080+00:00 app[web.1]: 
2017-08-03T15:58:04.235669+00:00 app[web.1]: Can't process request TypeError: Cannot read property 'result' of undefined
2017-08-03T15:58:04.235671+00:00 app[web.1]:     at ApiAiApp.extractData_ (/app/node_modules/actions-on-google/api-ai-app.js:1051:19)
2017-08-03T15:58:04.235672+00:00 app[web.1]:     at ApiAiApp.handleRequest (/app/node_modules/actions-on-google/assistant-app.js:499:10)
2017-08-03T15:58:04.235673+00:00 app[web.1]:     at /app/index.js:59:13
2017-08-03T15:58:04.235673+00:00 app[web.1]:     at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
2017-08-03T15:58:04.235674+00:00 app[web.1]:     at next (/app/node_modules/express/lib/router/route.js:137:13)
2017-08-03T15:58:04.235674+00:00 app[web.1]:     at Route.dispatch (/app/node_modules/express/lib/router/route.js:112:3)
2017-08-03T15:58:04.235675+00:00 app[web.1]:     at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
2017-08-03T15:58:04.235676+00:00 app[web.1]:     at /app/node_modules/express/lib/router/index.js:281:22
2017-08-03T15:58:04.235677+00:00 app[web.1]:     at Function.process_params (/app/node_modules/express/lib/router/index.js:335:12)
2017-08-03T15:58:04.235677+00:00 app[web.1]:     at next (/app/node_modules/express/lib/router/index.js:275:10)

**Comment by emouawad** [comment]
Sorry my mistake

**Comment by ry2659** [comment]
i am getting same error how i solve this.

**Comment by ry2659** [comment]
in dialogflow firebase
