### ISSUE TITLE
Build failure on latest version (1.2.1)

### ISSUE THREAD

**Issue by strttn** [actions-on-google/actions-on-google-nodejs#47]
Just did a new build on Heroku, which would have pulled the latest library version and got this build failure.

 /app/node_modules/actions-on-google/request-extractor.js:22 
 const { transformToSnakeCase } = require('./utils/transform'); 
       ^ 
 SyntaxError: Unexpected token { 
     at exports.runInThisContext (vm.js:53:16) 
     at Module._compile (module.js:387:25) 
     at Object.Module._extensions..js (module.js:422:10) 
     at Module.load (module.js:357:32) 
     at Function.Module._load (module.js:314:12) 
     at Module.require (module.js:367:17) 
     at require (internal/module.js:16:19) 
     at Object.<anonymous> (/app/node_modules/actions-on-google/assistant-app.js:24:26) 
     at Module._compile (module.js:413:34) 
     at Object.Module._extensions..js (module.js:422:10) 

I've rolled back to 1.1.0 for now and that's building fine.

**Comment by Canain** [comment]
Hello, thanks for creating an issue.
For debugging purposes, what version of Node.js are you using right now for Heroku? We support the current LTS Node.js version and up (currently v6.11.2+) so we can use the latest JavaScript ES6 features.

**Comment by strttn** [comment]
Thanks for the response. I'm currently running 5.9.1 so that must be the problem then.

I'll close this issue.
