### ISSUE TITLE
TypeError: this.response_.append is not a function

### ISSUE THREAD

**Issue by theunreal** [actions-on-google/actions-on-google-nodejs#95]
I'm trying to use `actions-on-google-nodejs` and Dialogflow, but when the event is triggered my bot won't respond and I get the following error:

```
error: Sending 500 ("Server Error") response:
 TypeError: this.response_.append is not a function
    at DialogflowApp.doResponse_ (my-proj\node_modules\actions-on-google\assistant-app.js:2202:20)
    at DialogflowApp.tell (my-proj\node_modules\actions-on-google\dialogflow-app.js:740:17)
    at makeName (my-proj\api\controllers\VersionController.js:62:13)
    at DialogflowApp.invokeIntentHandler_ (my-proj\node_modules\actions-on-google\assistant-app.js:2078:31)
    at DialogflowApp.handleRequestAsync (my-proj\node_modules\actions-on-google\assistant-app.js:535:19)
    at DialogflowApp.handleRequest (my-proj\node_modules\actions-on-google\assistant-app.js:424:10)
    at Object.getHookBugs (my-proj\api\controllers\VersionController.js:69:11)
    at wrapper (local\AppData\Roaming\npm\node_modules\sails\node_modules\@sailshq\lodash\lib\index.js:3250:19)
    at routeTargetFnWrapper (local\AppData\Roaming\npm\node_modules\sails\lib\router\bind.js:181:5)
    at callbacks (local\AppData\Roaming\npm\node_modules\sails\node_modules\@sailshq\express\lib\router\index.js:164:37)
    at param (local\AppData\Roaming\npm\node_modules\sails\node_modules\@sailshq\express\lib\router\index.js:138:11)
    at param (local\AppData\Roaming\npm\node_modules\sails\node_modules\@sailshq\express\lib\router\index.js:135:11)
    at pass (local\AppData\Roaming\npm\node_modules\sails\node_modules\@sailshq\express\lib\router\index.js:145:5)
    at nextRoute (local\AppData\Roaming\npm\node_modules\sails\node_modules\@sailshq\express\lib\router\index.js:100:7)
    at callbacks (local\AppData\Roaming\npm\node_modules\sails\node_modules\@sailshq\express\lib\router\index.js:167:11)
    at alwaysAllow (local\AppData\Roaming\npm\node_modules\sails\lib\hooks\policies\index.js:224:11)
    at routeTargetFnWrapper (local\AppData\Roaming\npm\node_modules\sails\lib\router\bind.js:181:5)
    at callbacks (local\AppData\Roaming\npm\node_modules\sails\node_modules\@sailshq\express\lib\router\index.js:164:37)
    at param (local\AppData\Roaming\npm\node_modules\sails\node_modules\@sailshq\express\lib\router\index.js:138:11)
    at param (local\AppData\Roaming\npm\node_modules\sails\node_modules\@sailshq\express\lib\router\index.js:135:11)
    at pass (local\AppData\Roaming\npm\node_modules\sails\node_modules\@sailshq\express\lib\router\index.js:145:5)
    at nextRoute (local\AppData\Roaming\npm\node_modules\sails\node_modules\@sailshq\express\lib\router\index.js:100:7)
```

my NodeJS code is simply this (I'm using SailsJS):

```
getHookBugs: function(req,res) {

    // a. the action name from the make_name Dialogflow intent
    const NAME_ACTION = 'listBugs';
    
      const app = new App({request: req, response: res});


      function makeName (app) {
        app.tell('Got here!');
      }
      // d. build an action map, which maps intent names to functions
      let actionMap = new Map();
      actionMap.set(NAME_ACTION, makeName);


      app.handleRequest(actionMap);
  }

```

**Comment by joelhegg** [comment]
I've run into issues myself with this library and `append` related to howardabrams/node-mocks-http/pull/156. It's only available in Express v4.11.0+, so not all Express-compatible libraries support it yet.

I don't know much about Sails.js. It says it sits on top of Express, but I believe it wraps Express rather than extends it. Looking at https://sailsjs.com/documentation/reference/response-res they don't seem to have `append` exposed.

**Comment by Canain** [comment]
The library currently uses `Express.request.append` to set some headers like the [accept JSON header here](https://github.com/actions-on-google/actions-on-google-nodejs/blob/ef01c100c4c9e2c95744842c4238127e1417262d/assistant-app.js#L2202).

If you are using Dialogflow, you should be able to just mock it to do nothing as it's not required.

A basic mock of this could be `req.append = function () {}` right before you use the client library but I'm not super familiar with Sails.js so you should figure out the best solution to mock it for Sails.js.

**Comment by Canain** [comment]
Now that we launched alpha for [v2 of the client library](https://medium.com/@silvano.luciani/actions-on-google-client-library-for-node-js-v2-0-0-alpha-c92361167f15), we standardized the abstraction for web frameworks with the generic [StandardHandler](https://github.com/actions-on-google/actions-on-google-nodejs/blob/c84ba000b6257b4d932e022658405e8661524625/src/framework/framework.ts#L74) taking in a JSON body and Headers and outputing a JSON body and a status code.

For express support currently in the v2 alpha, now we don't use `response.append` so try it out and give us any feedback so we can polish the library during the alpha.

**Comment by Canain** [comment]
Closing this now that [v2 is in general availability](https://developers.google.com/actions/reference/nodejs/lib-v1-migration).
